# Use an official Node.js runtime as the base image
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json (if exists)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the Node.js application code
COPY . .

# Build the Next.js app for production
RUN npm run build

# Expose the port the Node.js app will run on
EXPOSE 3777

# Command to run the Node.js app
CMD ["npm", "start"]